version: '3'
services:
  web:
    build: ./backend/python
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: kullanici
      POSTGRES_PASSWORD: sifre
      POSTGRES_DB: rehber
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
- ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
